version: '2.2'
services:
  es0-lab1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: es0-lab1
    environment:
      - node.name=es0-lab1
      - cluster.name=docker-cluster
      - discovery.seed_hosts=es1-lab1,es2-lab1
      - cluster.initial_master_nodes=es0-lab1,es1-lab1,es2-lab1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata0:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  es1-lab1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: es1-lab1
    environment:
      - node.name=es1-lab1
      - cluster.name=docker-cluster
      - discovery.seed_hosts=es0-lab1,es2-lab1
      - cluster.initial_master_nodes=es0-lab1,es1-lab1,es2-lab1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata1:/usr/share/elasticsearch/data
    ports:
      - 19200:9200
    networks:
      - esnet
  es2-lab1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: es2-lab1
    environment:
      - node.name=es2-lab1
      - cluster.name=docker-cluster
      - discovery.seed_hosts=es0-lab1,es1-lab1
      - cluster.initial_master_nodes=es0-lab1,es1-lab1,es2-lab1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata2:/usr/share/elasticsearch/data
    ports:
      - 29200:9200
    networks:
      - esnet
  kibana-lab1:
    image: docker.elastic.co/kibana/kibana:7.9.3
    container_name: kibana-lab1
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: http://es2-lab1:9200
    ports:
      - 5601:5601
    networks:
      - esnet
networks:
  esnet:
