version: '2.2'
services:
  elasticsearch0-lab1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: elasticsearch0-lab1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1-lab1,elasticsearch2-lab1"
      - "node.name=elasticsearch0-lab1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata0:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch1-lab1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: elasticsearch1-lab1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch0-lab1,elasticsearch2-lab1"
      - "node.name=elasticsearch1-lab1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata1:/usr/share/elasticsearch/data
    ports:
      - 19200:9200
    networks:
      - esnet
  elasticsearch2-lab1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: elasticsearch2-lab1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch0-lab1,elasticsearch1-lab1"
      - "node.name=elasticsearch2-lab1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata2:/usr/share/elasticsearch/data
    ports:
      - 29200:9200
    networks:
      - esnet
  kibana-lab1:
    image: docker.elastic.co/kibana/kibana:6.4.3
    container_name: kibana-lab1
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_URL: http://elasticsearch2-lab1:9200
    ports:
      - 5601:5601
    networks:
      - esnet
networks:
  esnet:
